#!/bin/bash
# Copyright 1999-2012 Gentoo Foundation
# Modified (butchered) by Milkey Mouse
# Distributed under the terms of the GNU General Public License v2

die() {
    code=$1; shift
    echo "$@" 1>&2
    exit $code
}

usage() {
	cat <<-EOF
	Usage: clang-config [options] [CC Profile]
	Give info about the current clang profile.

	Options:
	  -c, --get-current-profile  Print current used clang profile.
	  -l, --list-profiles        Print a list of available profiles.
	  -B, --get-bin-path         Print path where binaries of the given/current
	                             profile are located.
	  -L, --get-lib-path         Print path where libraries of the given/current
	                             profile are located.

	Profile names are of the form:  <CTARGET>-<version>
	For example:                    x86_64-gentoo-linux-musl-6.0.0
	EOF
	exit ${1:-1}
}
[[ $# -lt 1 ]] && usage 1

get_current_profile() {
	echo "x86_64-gentoo-linux-musl-6.0.0"
}

list_profiles() {
	echo " [1] $(get_current_profile) *"
}

get_bin_path() {
	echo "/usr/bin"
}

get_lib_path() {
	echo "/usr/lib/clang/6.0.0"
}

set_doit() {
	[[ -n ${DOIT} ]] && die "too many actions selected!"
	DOIT=$1
}
DOIT=""

for x in "$@" ; do
	case "${x}" in
		-c|--get-current-profile)
			set_doit get_current_profile
			;;
		-l|--list-profiles)
			set_doit list_profiles
			;;
		-B|--get-bin-path)
			set_doit get_bin_path
			;;
		-L|--get-lib-path)
			set_doit get_lib_path
			;;
		-C|--nocolor)
			;;
		-h|--help)
			usage 0
			;;
		-V|--version)
			echo "${argv0}: 0.1"
			exit 0
			;;
		-*)
			die "Invalid switch!  Run ${argv0} without parameters for help."
			;;
		*)
			;;
	esac
done

${DOIT}
